name: qcsd
base: core20
version: '0.1'
summary: Simple cli to control your spotify devices
description: |
  The qcsd cli aims to make life easier when you want to 
  control your spotify devices easily. Allowing you to increase/decrease
  volume directly on the device, change the active player to another one and so on.

grade: devel
confinement: strict

parts:
  qcsd:
    plugin: npm
    source: .
    npm-node-version: 14.16.1


apps:
  qcsd:
    command: bin/qcsd
